# Generated by Django 4.2.6 on 2026-04-09 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encabezado', models.CharField(max_length=225)),
                ('bajada', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('portada', models.ImageField(upload_to='news/')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='news/')),
                ('descricion', models.CharField(max_length=255)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='newsPortal.noticias')),
            ],
        ),
        migrations.CreateModel(
            name='Parrafos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitulo', models.CharField(blank=True, max_length=225)),
                ('cuerpo', models.TextField()),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parrafos', to='newsPortal.noticias')),
            ],
        ),
        migrations.CreateModel(
            name='Imgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='news/')),
                ('descricion', models.CharField(max_length=255)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='newsPortal.noticias')),
            ],
        ),
    ]
