# Generated by Django 4.2.6 on 2026-04-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autors', models.TextField()),
                ('titulo', models.TextField()),
                ('fecha', models.DateField()),
                ('magazine', models.TextField()),
                ('doi', models.URLField()),
                ('url', models.URLField()),
            ],
        ),
    ]
