# Generated by Django 4.2.6 on 2026-04-09 06:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fragmento', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='areas/')),
                ('icono', models.FileField(blank=True, null=True, upload_to='areas/iconos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])])),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('titulo', models.CharField(blank=True, max_length=50)),
                ('academic_rank', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('g_scholar', models.CharField(blank=True, max_length=100)),
                ('img', models.ImageField(upload_to='members/')),
                ('descripcion', models.TextField()),
                ('puesto', models.CharField(blank=True, max_length=50)),
                ('universidad', models.CharField(blank=True, max_length=50)),
                ('area', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='membersApp.area')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas_responsable', to='membersApp.members'),
        ),
    ]
