# Generated by Django 4.2.6 on 2026-02-09 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='areas/'),
        ),
        migrations.AddField(
            model_name='area',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas_responsable', to='membersApp.members'),
        ),
    ]
