# Generated by Django 4.2.6 on 2026-02-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membersApp', '0002_area_portada_area_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='fragmento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
