# Generated by Django 4.2.6 on 2026-02-10 02:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membersApp', '0003_area_fragmento'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='icono',
            field=models.FileField(blank=True, null=True, upload_to='areas/iconos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])]),
        ),
    ]
